name: simple_audio
description: A simple cross-platform solution for playing audio in Flutter.
version: 2.0.1
homepage: https://github.com/erikas-taroza/simple_audio
repository: https://github.com/erikas-taroza/simple_audio
topics:
  - audio
  - audio-player
  - music
  - player

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.82.1
  meta: ^1.8.0
  freezed_annotation: ^2.4.1
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^9.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  analyzer: ^6.4.1

flutter:
  plugin:
    platforms:
      android:
        package: com.erikas.simple_audio
        pluginClass: SimpleAudioPlugin
      ios:
        pluginClass: SimpleAudioPlugin
      linux:
        pluginClass: SimpleAudioPlugin
      macos:
        pluginClass: SimpleAudioPlugin
      windows:
        pluginClass: SimpleAudioPluginCApi
